# URL for GTFS feeds from 2015 to 2021

transit.feeds.url <- list(Fall= list(`2015`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20151011/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20151113/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20150924/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20151009/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20150925/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20151011/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20151216/download','WSF','Washington State Ferries')),
                                     `2016`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20161024/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20161024/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20161004/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20161206/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20161024/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20161024/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20161014/download','WSF','Washington State Ferries')),
                                     `2017`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20171019/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20171019/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20170923/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20171021/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20171018/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20171020/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20171015/download','WSF','Washington State Ferries')),
                                     `2018`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20181014/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20181013/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20180925/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20180928/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20181013/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20181013/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20181012/download','WSF','Washington State Ferries')),
                                     `2019`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20191014/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20191019/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20191008/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20191016/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20191011/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20191019/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20191011/download','WSF','Washington State Ferries')),
                                     `2020`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20201012/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20201010/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20201016/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20201027/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20201009/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20201010/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20201016/download','WSF','Washington State Ferries')),
                                     `2021`=list("ct" = c('','CT','Community Transit'),
                                                 "et" = c('','ET','Everett Transit'),
                                                 "kcm" = c('','KCM','King County Metro'),
                                                 "kt" = c('','KT','Kitsap Transit'),
                                                 "pt" = c('','PT','Pierce Transit'),
                                                 "st" = c('','ST','Sound Transit'),
                                                 "wsf" = c('','WSF','Washington State Ferries'))
                                     ),
                          Spring= list(`2015`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20150507/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20150427/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20150527/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20150315/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20150427/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20150317/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20151216/download','WSF','Washington State Ferries')),
                                     `2016`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20160519/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20160519/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20160516/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20160422/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20160519/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20160504/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20160515/download','WSF','Washington State Ferries')),
                                     `2017`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20170511/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20170509/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20170420/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20170513/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20170509/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20170511/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20170509/download','WSF','Washington State Ferries')),
                                     `2018`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20180508/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20180508/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20180511/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20180509/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20180509/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20180508/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20180511/download','WSF','Washington State Ferries')),
                                     `2019`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20190504/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20190509/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20190509/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20190504/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20190510/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20190510/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20190517/download','WSF','Washington State Ferries')),
                                     `2020`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20200421/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20200514/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20200323/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20200507/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20200514/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20200514/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20200508/download','WSF','Washington State Ferries')),
                                     `2021`=list("ct" = c('https://transitfeeds.com/p/community-transit/454/20210321/download','CT','Community Transit'),
                                                 "et" = c('https://transitfeeds.com/p/everett-transit/455/20210407/download','ET','Everett Transit'),
                                                 "kcm" = c('https://transitfeeds.com/p/king-county-metro/73/20210520/download','KCM','King County Metro'),
                                                 "kt" = c('https://transitfeeds.com/p/kitsap-transit/296/20210511/download','KT','Kitsap Transit'),
                                                 "pt" = c('https://transitfeeds.com/p/pierce-transit/448/20210407/download','PT','Pierce Transit'),
                                                 "st" = c('https://transitfeeds.com/p/sound-transit/44/20210407/download','ST','Sound Transit'),
                                                 "wsf" = c('https://transitfeeds.com/p/washington-state-ferries/586/20210514/download','WSF','Washington State Ferries'))
                          ))
